### ISSUE TITLE
Targets to make vulkan_sdk_linux/etc available

### ISSUE THREAD

**Issue by joelwilliamson** [zaucy/rules_vulkan#3]
I have some `filegroup` targets in my fork to make the contents of `etc` as well as the `lib/libVkLayer*.so` objects available to my test and binary targets. Is that something you'd be interested in merging into your repo? I could try to put together versions of the targets for macos and windows, but I wouldn't be able to test for either platform.

**Comment by zaucy** [comment]
How about exporting all the files so that whatever filegroup you need now or in the future can be adjusted at the user level. 
https://github.com/zaucy/rules_vulkan/pull/4 Let me know what you think!

I'd be hesitant to add filegroups unless we could confidentally create them on all platforms and put them in the `@vulkan_sdk` repository rule.

**Comment by joelwilliamson** [comment]
That seems like a good solution
